### ISSUE TITLE
Pick List Values

### ISSUE THREAD

**Issue by MartinBernard** [hres/wireframes#2]
Vinay / Kat / or - to provide a complete picklist of values for all drop down menus for 4 forms.

**Comment by MartinBernard** [comment]
Some include... 
dosage form  
regulatory activity type
regulatory activity lead
fee class

**Comment by kpaschakis** [comment]
Hi Chi - I created a list of where you can find the values for the drop down menus. Please see last tab on attached spreadsheet:
[REP - Form Field View v9.1.xlsx](https://github.com/hres/wireframes/files/103812/REP.-.Form.Field.View.v9.1.xlsx)

You can start with the pick lists highlighted in yellow. I am still gathering the values for all of the other pick lists.  

In case you don't have it already, here is the link to the HC3011 form where many of the pick list values can be found: http://www.hc-sc.gc.ca/dhp-mps/alt_formats/pdf/prodpharma/applic-demande/form/hc3011_sc3011-eng.pdf

Feel free to message me or drop by if you have any questions.

**Comment by MartinBernard** [comment]
@kpaschakis - what are the missing values, I may already have them if it's terms captured under controlled vocabularies?

**Comment by cqpham** [comment]
@MartinBernard and @kpaschakis 
I've finished adding all the html pages except for the HC Internal ones. I'm still waiting for the rest of the drop down menu values.

**Comment by kpaschakis** [comment]
3 outstanding are: RA Lead,  Fee Class, sequence description. 

1) Fee class:  I have these values - need to confirm them with Vianney now that he is back. Will do that this afternoon at REP meeting. 

2) RA Lead:  We don't know what these values are. Need to confirm with Vianney. Also on agenda for REP this aft. 

3: Sequence description - getting from Denis. 

@MartinBernard  and @cqpham

**Comment by MartinBernard** [comment]
@cqpham - pls note that @kpaschakis will be putting additional requirements in GITHub in addition to this one. Note that oyu have the go ahead to now spend 50% of your time on these new requirements

**Comment by kpaschakis** [comment]
@cqpham Here is the spreadseet containing list values for Dossier, RA, and Sequence description pick lists.  
[Sequence Description - pick list values.docx.xlsx](https://github.com/hres/wireframes/files/155300/Sequence.Description.-.pick.list.values.docx.xlsx)

Note - for Dossier pick list, there are only 2 options at the moment (Pharmaceutical and biologic). All RAs are applicable to those dossiers EXCEPT for YPBR. This RA is only used for Biologic dossiers.  This is reflected in Tab 1. Otherwise, tab 2 might be most useful for you in building the cascading picklist.  Let me know if you have questions.

**Comment by MartinBernard** [comment]
@kpaschakis - can we close this?
