### ISSUE TITLE
Wireframe Update?

### ISSUE THREAD

**Issue by MartinBernard** [hres/wireframes#8]
@kpaschakis - I need Chi on conversion full time. I assume she's almost done given that she's been developping the wireframes for almost one month now. I want to make sure we're not over doing it. 

If so, please close all issues.

Please provide update by replying to this.

**Comment by kpaschakis** [comment]
@MartinBernard 

@cqpham  has done minimal work on REP since you left. 

Vianney reviewed the wireframes last week and provided feedback. Chi incorporated those changes (see issue #9 for list of modifications V requested) and spent approx. 5 hours total making these updates.

 We are still waiting for the pick list values for sequence description before I can close issue #2 .  Chi has estimated the remaining work to incorporating cascading pick list values for sequence description to be approx. 1-2 hours. 

I have been very clear that REP work is not her priority over conversions and have been keeping S-E and Scott in the loop regarding Chi's time on these wireframes to ensure there are no negative impacts on the conversion schedule.

**Comment by MartinBernard** [comment]
Excellent. Thank you. 
 
 
 
 Sent from my BlackBerry 10 smartphone on the Rogers network.
   
 
   From: kpaschakis
    Sent: Thursday, February 11, 2016 3:59 PM
    To: hres/wireframes
    Reply To: hres/wireframes
    Cc: MartinBernard
    Subject: Re: [wireframes] Wireframe Update? (#8)
 
 @MartinBernard  
 @cqpham has done minimal work on REP since you left.  
 Vianney reviewed the wireframes last week and provided feedback. Chi incorporated those changes (see issue #9 for list of modifications V requested) and spent approx. 5 hours total making these updates. 
 We are still waiting for the pick list values for sequence description before I can close issue #2 . Chi has estimated the remaining work to incorporating cascading pick list values for sequence description to be approx. 1-2 hours.  
 I have been very clear that REP work is not her priority over conversions and have been keeping S-E and Scott in the loop regarding Chi's time on these wireframes to ensure there are no negative impacts on the conversion schedule.
